services:
  web:
    build: .

    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - redis

  redis:
    image: redis:alpine

    container_name: redis-server


  nginx:
    image: nginx:alpine
    container_name: nginx-proxy

    ports:
      - "80:80"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - web

